name: "Deploy site"

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Fetch gh-pages branch"
        run: git fetch origin gh-pages --depth=1
      - name: "Set permissions"
        run: chmod -R a+rwX $(pwd)
      - name: "Build site"
        run: |
          podman run -it -v $(pwd):/mnt -w /mnt --userns=keep-id \
                 quay.io/openssl-ci/docs:20240711-115832 sh -c "\
                   git config --global --add safe.directory /mnt && \
                   python build.py master"
      - name: "Fix ownership"
        run: sudo chown -R "${USER:-$(id -un)}" $(pwd)

